version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    mem_limit: 200m

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    mem_limit: 150m

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - backend
    mem_limit: 50m

volumes:
  rabbitmq_data:
  postgres_data:
  redis_data:

networks:
  backend:
    name: backend