version: '3.9'

services:
  vehicle:
    build:
      context: .
      dockerfile: ./apps/vehicle/Dockerfile
    ports:
      - '4001:5001'
    env_file:
      - .env
    command: npm run start:vehicle
    networks:
      - backend
    mem_limit: 100m
    restart: always

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    command: sh -c "npm run migration:run:prod && npm run start:user"
    networks:
      - backend
    mem_limit: 100m
    restart: always

networks:
  backend:
    external: true