version: '3.9'

services:
  vehicle:
    build:
      context: .
      dockerfile: ./apps/vehicle/Dockerfile
    ports:
      - '4001:5001'
    env_file:
      - .env
    command: npm run start:dev vehicle
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 200M

  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    command: >
      sh -c "npm run migration:run && npm run start:dev user"
    networks:
      - backend
    deploy:
      resources:
        limits:
          memory: 600M

networks:
  backend:
    external: true